# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33a38c85f23b229dd4d3b5e6a61950ad0def22b306b094de4b4c0c20870f05e4c9fbdb330da1eee420543348e5c8a93cc7c4901474a889c1968636fb82ad8a05

test:
  secret_key_base: 8d71077931edbd5996347a8ce744b7c36d526554dbbac4f5a13ffd6659fe83a8e8911b503e3ad7a9bbb98dec284c35bb500f9d1e82fc9a69e68c52b3a99b1dfe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
